import Link from "next/link";
import { ArrowRight, BadgeCheck, Boxes, CircleCheck, CreditCard, PackageCheck, Search, ShieldCheck, Store, Truck } from "lucide-react";

export default function HowItWorksPage() {
  return <main className="shell page-main"><div className="breadcrumb"><Link href="/">Ana sayfa</Link> / Nasıl çalışır?</div><div className="page-heading" style={{ maxWidth: 660 }}><span className="eyebrow">DAMPINGVAR REHBERİ</span><h1>Parçayı seçmek de, süreci takip etmek de kolay.</h1><p>Merkezi OEM kataloğumuz parçanın kimliğini tanımlar. Mağazalar markasını, ürün tipini, fiyatını ve stok bilgisini ayrı ayrı sunar.</p></div>
    <div className="why-grid" style={{ margin: "35px 0", color: "#192525" }}>
      {[{ icon: <Search size={24} />, n: "01", title: "Parçayı bul", text: "Araç bilgilerin veya OEM numarasıyla merkezi katalogda ara. Bulamazsan mağazalara teklif talebi gönder." },{ icon: <Boxes size={24} />, n: "02", title: "Teklifleri karşılaştır", text: "Aynı OEM'e bağlı farklı mağazaların fiyatını, markasını ve ürün tipini yan yana gör." },{ icon: <Truck size={24} />, n: "03", title: "Tek sepetle satın al", text: "Farklı mağazalardan alacağın parçaları tek sepete ekle. Her mağaza kendi gönderisini hazırlar ve faturasını düzenler." }].map((x) => <div className="surface surface-pad" key={x.n}><span className="eyebrow">ADIM {x.n}</span><div className="why-icon">{x.icon}</div><h3 style={{ fontWeight: 800, fontSize: 18 }}>{x.title}</h3><p className="muted small-text" style={{ lineHeight: 1.7 }}>{x.text}</p></div>)}
    </div>
    <div className="surface surface-pad" style={{ marginBottom: 25 }}><span className="eyebrow"><ShieldCheck size={15} /> ÜRÜN TİPLERİ</span><h2 className="page-title" style={{ fontSize: 25 }}>Her teklif ne aldığını açıkça söyler.</h2><div className="panel-grid" style={{ gridTemplateColumns: "repeat(3,1fr)", marginTop: 20 }}><div className="help-card"><h3><BadgeCheck size={18} style={{ display: "inline" }} /> Orijinal</h3><p>Üretici / OEM markalı orijinal ürün. Etiket: <strong>ORİJİNAL</strong>.</p></div><div className="help-card"><h3>⚙ Yan Sanayi</h3><p>OEM dışındaki üreticinin ürettiği parça. Etiket: <strong>YAN SANAYİ</strong>.</p></div><div className="help-card"><h3>◇ Muadil</h3><p>İstenen OEM parçaya teknik olarak alternatif ürün. Etiket: <strong>MUADİL</strong>.</p></div></div><div className="notice notice-info"><CircleCheck size={17} /> En düşük fiyatlı ürün otomatik olarak orijinal kabul edilmez. Karar verirken etiket ve marka bilgisine bak.</div></div>
    <div className="panel-grid"><div className="surface surface-pad"><CreditCard size={25} color="#6b8e53" /><h3 className="surface-title" style={{ marginTop: 13 }}>Ödeme ve gönderim</h3><p className="muted small-text" style={{ lineHeight: 1.7 }}>Kart ödemesi yapılandırılmış iyzico altyapısında, banka transferi ise finans onayından sonra işlenir. Her mağaza için ayrı kargo takip bilgisi sağlanır.</p></div><div className="surface surface-pad"><PackageCheck size={25} color="#6b8e53" /><h3 className="surface-title" style={{ marginTop: 13 }}>Teslimat sonrası hakediş</h3><p className="muted small-text" style={{ lineHeight: 1.7 }}>Mağazanın hakedişi kendi alt siparişi teslim edildikten sonra oluşur. Mağaza satış faturasını müşteriye, DampingVar komisyon/hizmet faturasını mağazaya düzenler.</p></div></div>
    <div className="seller-strip" style={{ marginTop: 40 }}><div><span className="eyebrow">HAZIR MISIN?</span><h2>Doğru parçayı birlikte bulalım.</h2></div><Link href="/parcalar" className="btn btn-dark">Parçaları keşfet <ArrowRight size={16} /></Link></div>
  </main>;
}
