import Link from "next/link";
import { and, count, desc, eq, inArray } from "drizzle-orm";
import { ArrowRight, BadgeCheck, Boxes, ClipboardList, CreditCard, FileQuestion, Landmark, Package, Search, ShieldCheck, Store, Wallet } from "lucide-react";
import { db } from "@/db";
import { auditLogs, callRequests, categories, commissionInvoices, commissionRules, oemProductRequests, orderItems, orders, payments, platformSettings, products, quoteOffers, quoteRequests, shipments, storeBalances, storeOrders, storePayouts, storeProducts, stores, users } from "@/db/schema";
import { adminCorrectOfferAction, approveOemRequestAction, createCatalogProductAction, createCategoryAction, createPayoutAction, createVehicleFitmentAction, issueCommissionInvoiceAction, markPayoutPaidAction, recordRefundAction, rejectOemRequestAction, reviewStoreAction, saveBankDetailsAction, savePayoutPeriodAction, updateCatalogProductAction, updateCommissionAction, verifyBankPaymentAction } from "@/app/actions/admin";
import { EmptyState, TypeBadge } from "@/components/catalog-ui";
import { requireAdmin } from "@/lib/auth";
import { formatDate, formatPrice, productTypeLabels } from "@/lib/core";

export const dynamic = "force-dynamic";
const tabs = [["genel", "Genel Bakış"], ["katalog", "OEM Kataloğu"], ["oem", "OEM Talepleri"], ["magazalar", "Mağazalar"], ["urunler", "Mağaza Ürünleri"], ["siparisler", "Siparişler"], ["odemeler", "Ödemeler"], ["finans", "Finans & Faturalar"], ["teklifler", "Teklifler"], ["canli", "Live"], ["audit", "Audit"]] as const;
export default async function AdminPage({ searchParams }: { searchParams: Promise<{ tab?: string; error?: string; success?: string }> }) {
  await requireAdmin();
  const query = await searchParams, tab = tabs.some(([k]) => k === query.tab) ? query.tab || "genel" : "genel";
  return <main className="shell page-main"><div className="breadcrumb"><Link href="/">Ana sayfa</Link> / Yönetim paneli</div><div className="page-heading"><span className="eyebrow"><ShieldCheck size={14} /> DAMPINGVAR YÖNETİMİ</span><h1>Kontrol merkezi.</h1><p>Kataloğu, mağazaları, ödeme doğrulamasını ve teslimat sonrası finans akışını yönet.</p></div>
    {query.error && <div className="notice notice-error">{query.error}</div>}{query.success && <div className="notice notice-success"><BadgeCheck size={16} /> {query.success}</div>}
    <nav className="panel-nav">{tabs.map(([key, label]) => <Link key={key} href={`/admin?tab=${key}`} className={tab === key ? "active" : ""}>{label}</Link>)}</nav>
    {tab === "genel" && <AdminOverview />}{tab === "katalog" && <CatalogTab />}{tab === "oem" && <OemTab />}{tab === "magazalar" && <StoresTab />}{tab === "urunler" && <OffersTab />}{tab === "siparisler" && <OrdersTab />}{tab === "odemeler" && <PaymentsTab />}{tab === "finans" && <FinanceTab />}{tab === "teklifler" && <QuotesTab />}{tab === "canli" && <LiveTab />}{tab === "audit" && <AuditTab />}
  </main>;
}

async function AdminOverview() {
  const [[productsCount], [storesCount], [ordersCount], [quotesCount]] = await Promise.all([
    db.select({ total: count() }).from(products), db.select({ total: count() }).from(stores), db.select({ total: count() }).from(orders), db.select({ total: count() }).from(quoteRequests),
  ]);
  return <div className="stack"><div className="metric-grid"><div className="metric-card"><span><Boxes size={15} /> Merkezi ürünler</span><strong>{productsCount.total}</strong><small>Tekilleştirilmiş OEM</small></div><div className="metric-card"><span><Store size={15} /> Mağazalar</span><strong>{storesCount.total}</strong><small>Başvurular dahil</small></div><div className="metric-card"><span><Package size={15} /> Siparişler</span><strong>{ordersCount.total}</strong><small>Üst siparişler</small></div><div className="metric-card"><span><ClipboardList size={15} /> Parça talepleri</span><strong>{quotesCount.total}</strong><small>Müşteri talepleri</small></div></div><div className="panel-grid"><Link href="/admin?tab=oem" className="surface surface-pad"><FileQuestion color="#6e8e58" size={27} /><h3 className="surface-title" style={{ marginTop: 13 }}>OEM taleplerini incele</h3><p className="muted small-text">Bilinmeyen OEM'ler merkezi kataloğa yalnızca yönetici onayıyla eklenir.</p><span className="section-link">Taleplere git <ArrowRight size={15} /></span></Link><Link href="/admin?tab=odemeler" className="surface surface-pad"><CreditCard color="#6e8e58" size={27} /><h3 className="surface-title" style={{ marginTop: 13 }}>Ödemeleri doğrula</h3><p className="muted small-text">EFT ödemeleri gerçek banka hareketi doğrulanmadan onaylanmaz.</p><span className="section-link">Ödemelere git <ArrowRight size={15} /></span></Link></div></div>;
}

async function CatalogTab() {
  const [catalog, taxonomy] = await Promise.all([db.select().from(products).orderBy(desc(products.createdAt)).limit(200), db.select().from(categories).orderBy(categories.sortOrder)]);
  return <div className="stack"><div className="panel-grid"><div className="surface surface-pad"><h2 className="surface-title">Merkezi OEM ürünü ekle</h2><p className="muted small-text">Aynı normalize OEM yalnızca bir ürün olabilir. Marka ve ürün tipi bu kayda girilmez.</p><form action={createCatalogProductAction}><label className="form-field"><span>OEM numarası *</span><input name="oemNo" required placeholder="Üretici parça numarası" /></label><label className="form-field"><span>Standart ürün adı *</span><input name="productName" required placeholder="Örn. Ön Fren Balatası" /></label><label className="form-field"><span>Kategori</span><select name="categoryId"><option value="">Kategori seçin</option>{taxonomy.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="field-grid"><label className="form-field"><span>Birim</span><input name="unit" defaultValue="Adet" /></label><label className="form-field"><span>Açıklama</span><input name="description" /></label></div><button type="submit" className="btn btn-accent">Merkezi Ürün Oluştur</button></form></div>
      <div className="stack"><div className="surface surface-pad"><h2 className="surface-title">Kategori ekle</h2><form action={createCategoryAction} className="field-grid"><label className="form-field"><span>Kategori adı *</span><input name="name" required /></label><label className="form-field"><span>Üst kategori (isteğe bağlı)</span><select name="parentId"><option value="">Ana kategori</option>{taxonomy.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button type="submit" className="btn btn-outline btn-small">Kategori Ekle</button></form></div><div className="surface surface-pad"><h2 className="surface-title">Merkezi araç uyumluluğu</h2><form action={createVehicleFitmentAction}><label className="form-field"><span>Merkezi ürün *</span><select name="productId" required defaultValue=""><option value="" disabled>Ürün seçin</option>{catalog.map((p) => <option key={p.id} value={p.id}>{p.oemNo} · {p.productName}</option>)}</select></label><div className="field-grid"><label className="form-field"><span>Araç markası *</span><input name="brand" required /></label><label className="form-field"><span>Model *</span><input name="model" required /></label><label className="form-field"><span>Başlangıç yılı</span><input type="number" name="yearFrom" min="1950" max="2100" /></label><label className="form-field"><span>Bitiş yılı</span><input type="number" name="yearTo" min="1950" max="2100" /></label></div><label className="form-field"><span>Motor</span><input name="engine" /></label><button type="submit" className="btn btn-outline btn-small">Uyumluluk Ekle</button></form></div></div></div>
    <div className="surface surface-pad"><h2 className="surface-title">Merkezi katalog ({catalog.length})</h2>{catalog.length ? <div className="data-table-wrap"><table className="data-table"><thead><tr><th>OEM</th><th>Ürün / Açıklama</th><th>Durum</th><th>Güncelle</th></tr></thead><tbody>{catalog.map((p) => <tr key={p.id}><td><strong>{p.oemNo}</strong><div className="muted">{p.normalizedOem}</div></td><td><strong>{p.productName}</strong><div className="muted">{p.description?.slice(0, 75)}</div></td><td><span className={`status-badge status-${p.isActive ? "active" : "suspended"}`}>{p.isActive ? "Aktif" : "Pasif"}</span></td><td><details><summary style={{ cursor: "pointer", fontSize: 11, fontWeight: 800 }}>Düzenle</summary><form action={updateCatalogProductAction} style={{ paddingTop: 9, minWidth: 230 }}><input type="hidden" name="id" value={p.id} /><label className="form-field"><span>Standart ürün adı</span><input name="productName" defaultValue={p.productName} required /></label><label className="form-field"><span>Açıklama</span><input name="description" defaultValue={p.description || ""} /></label><label className="checkbox-row"><input type="checkbox" name="isActive" defaultChecked={p.isActive} /> Aktif</label><button className="btn btn-dark btn-small" style={{ marginTop: 9 }} type="submit">Kaydet</button></form></details></td></tr>)}</tbody></table></div> : <EmptyState title="Merkezi katalog boş" description="Gerçek OEM kayıtlarını yukarıdaki formdan oluştur. Örnek veya sahte ürün eklenmez." />}</div>
  </div>;
}

async function OemTab() {
  const requests = await db.select({ request: oemProductRequests, storeName: stores.name }).from(oemProductRequests).innerJoin(stores, eq(oemProductRequests.storeId, stores.id)).orderBy(desc(oemProductRequests.createdAt));
  const taxonomy = await db.select().from(categories);
  return <div className="surface surface-pad"><h2 className="surface-title">Bilinmeyen OEM talepleri ({requests.length})</h2>{requests.length ? requests.map(({ request, storeName }) => <div className="list-card" key={request.id} style={{ display: "block" }}><div className="page-heading-row"><div><h3 style={{ fontSize: 15 }}>{request.oemNo} <span className={`status-badge status-${request.status}`}>{request.status}</span></h3><p>Mağaza: {storeName} · Öneri: {request.suggestedName || "Yok"} · {formatDate(request.createdAt)}</p></div></div>{request.status === "pending" && <div className="form-actions" style={{ marginTop: 15 }}><form action={approveOemRequestAction} style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><input type="hidden" name="id" value={request.id} /><input className="form-input" name="productName" defaultValue={request.suggestedName || ""} placeholder="Standart ürün adı *" required style={{ width: 210 }} /><select name="categoryId" className="form-input" style={{ width: 160 }}><option value="">Kategori seçin</option>{taxonomy.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="btn btn-accent btn-small" type="submit">Onayla & Kataloğa Ekle</button></form><form action={rejectOemRequestAction}><input type="hidden" name="id" value={request.id} /><button type="submit" className="btn btn-danger btn-small">Reddet</button></form></div>}</div>) : <EmptyState title="Bekleyen OEM talebi yok" description="Mağazaların katalogda bulamadığı OEM numaraları burada incelenir." />}</div>;
}

async function StoresTab() {
  const rows = await db.select({ store: stores, ownerName: users.name, email: users.email }).from(stores).innerJoin(users, eq(stores.ownerId, users.id)).orderBy(desc(stores.createdAt));
  return <div className="surface surface-pad"><h2 className="surface-title">Mağazalar ({rows.length})</h2>{rows.length ? <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Mağaza</th><th>Yetkili</th><th>Şehir</th><th>Komisyon</th><th>Durum / İşlem</th></tr></thead><tbody>{rows.map(({ store, ownerName, email }) => <tr key={store.id}><td><strong>{store.name}</strong><div className="muted">{formatDate(store.createdAt)}</div></td><td>{ownerName}<div className="muted">{email}</div></td><td>{store.city || "-"}</td><td>%{store.commissionRate}</td><td><span className={`status-badge status-${store.status}`}>{store.status}</span><form action={reviewStoreAction} className="inline-form" style={{ marginTop: 7 }}><input type="hidden" name="id" value={store.id} /><select name="status" defaultValue={store.status} className="mini-select"><option value="pending">Beklemede</option><option value="approved">Onaylı</option><option value="suspended">Askıda</option></select><button type="submit" className="btn btn-outline btn-small">Kaydet</button></form></td></tr>)}</tbody></table></div> : <EmptyState title="Henüz mağaza başvurusu yok" description="Başvurular burada görünecek." />}</div>;
}

async function OffersTab() {
  const rows = await db.select({ offer: storeProducts, productName: products.productName, oemNo: products.oemNo, storeName: stores.name }).from(storeProducts).innerJoin(products, eq(storeProducts.catalogProductId, products.id)).innerJoin(stores, eq(storeProducts.storeId, stores.id)).orderBy(desc(storeProducts.createdAt)).limit(150);
  return <div className="surface surface-pad"><h2 className="surface-title">Mağaza teklifleri ({rows.length})</h2>{rows.length ? <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Merkezi ürün</th><th>Mağaza / SKU</th><th>Marka ve tip</th><th>Fiyat / Stok</th><th>Admin düzeltme</th></tr></thead><tbody>{rows.map(({ offer, productName, oemNo, storeName }) => <tr key={offer.id}><td><strong>{productName}</strong><div className="muted">OEM: {oemNo}</div></td><td>{storeName}<div className="muted">{offer.storeSku}</div></td><td>{offer.brand}<div><TypeBadge type={offer.productType} compact /></div></td><td>{formatPrice(offer.price)}<div className="muted">{offer.stock} adet</div></td><td><form action={adminCorrectOfferAction} className="inline-form"><input type="hidden" name="id" value={offer.id} /><input name="brand" className="mini-input" defaultValue={offer.brand} required /><select name="productType" className="mini-select" defaultValue={offer.productType}>{Object.entries(productTypeLabels).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select><button type="submit" className="btn btn-dark btn-small">Düzelt</button></form></td></tr>)}</tbody></table></div> : <EmptyState title="Henüz mağaza teklifi yok" description="Onaylı mağazalar merkezi katalog ürünlerine teklif eklediğinde burada görünür." />}</div>;
}

async function OrdersTab() {
  const rows = await db.select({ order: orders, customer: users.email }).from(orders).innerJoin(users, eq(orders.userId, users.id)).orderBy(desc(orders.createdAt)).limit(100);
  const ids = rows.map((r) => r.order.id);
  const parts = ids.length ? await db.select({ part: storeOrders, storeName: stores.name }).from(storeOrders).innerJoin(stores, eq(storeOrders.storeId, stores.id)).where(inArray(storeOrders.orderId, ids)) : [];
  return <div className="surface surface-pad"><h2 className="surface-title">Siparişler ({rows.length})</h2>{rows.length ? rows.map(({ order, customer }) => <div className="list-card" key={order.id}><div><h3><Link href={`/siparisler/${order.id}`}>#{order.orderNumber}</Link> · {formatPrice(order.total)}</h3><p>{customer} · {formatDate(order.createdAt)} · {parts.filter((p) => p.part.orderId === order.id).map((p) => `${p.storeName}: ${p.part.status}`).join(" / ")}</p></div><span className={`status-badge status-${order.status}`}>{order.status}</span></div>) : <EmptyState title="Henüz sipariş yok" description="Müşteri siparişleri burada listelenecek." />}</div>;
}

async function PaymentsTab() {
  const rows = await db.select({ payment: payments, orderNumber: orders.orderNumber, email: users.email }).from(payments).innerJoin(orders, eq(payments.orderId, orders.id)).innerJoin(users, eq(orders.userId, users.id)).orderBy(desc(payments.createdAt)).limit(150);
  return <div className="surface surface-pad"><div className="notice notice-info">EFT, bankada gerçekten görülen tahsilat doğrulanmadan <strong>paid</strong> yapılmamalıdır. Müşterinin gönderdiği referans tek başına yeterli değildir.</div><h2 className="surface-title">Ödeme kayıtları</h2>{rows.length ? <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Sipariş</th><th>Müşteri</th><th>Yöntem / Durum</th><th>Tutar</th><th>Doğrulama</th></tr></thead><tbody>{rows.map(({ payment, orderNumber, email }) => <tr key={payment.id}><td><strong>#{orderNumber}</strong><div className="muted">{formatDate(payment.createdAt)}</div></td><td>{email}</td><td>{payment.method === "card" ? "iyzico" : "EFT"}<div><span className={`status-badge status-${payment.status}`}>{payment.status}</span></div></td><td>{formatPrice(payment.amount)}</td><td>{payment.status === "pending_verification" && payment.method === "bank_transfer" ? <form action={verifyBankPaymentAction} className="inline-form"><input type="hidden" name="orderId" value={payment.orderId} /><input className="mini-input" name="reference" placeholder="Banka referansı" required /><button className="btn btn-accent btn-small" type="submit">Onayla</button></form> : <span className="muted small-text">{payment.reference || "-"}</span>}</td></tr>)}</tbody></table></div> : <EmptyState title="Henüz ödeme yok" description="Checkout ile oluşturulan gerçek ödeme kayıtları burada görüntülenecek." />}</div>;
}

async function FinanceTab() {
  const [balances, payoutRows, invoiceRows, settings, storesList, refundRows] = await Promise.all([
    db.select({ balance: storeBalances, storeName: stores.name }).from(storeBalances).innerJoin(stores, eq(storeBalances.storeId, stores.id)),
    db.select({ payout: storePayouts, storeName: stores.name }).from(storePayouts).innerJoin(stores, eq(storePayouts.storeId, stores.id)).orderBy(desc(storePayouts.createdAt)).limit(80),
    db.select({ invoice: commissionInvoices, storeName: stores.name }).from(commissionInvoices).innerJoin(stores, eq(commissionInvoices.storeId, stores.id)).orderBy(desc(commissionInvoices.createdAt)).limit(80),
    db.select().from(platformSettings), db.select({ id: stores.id, name: stores.name, rate: stores.commissionRate }).from(stores),
    db.select({ part: storeOrders, orderNumber: orders.orderNumber, method: orders.paymentMethod, storeName: stores.name }).from(storeOrders).innerJoin(orders, eq(storeOrders.orderId, orders.id)).innerJoin(stores, eq(storeOrders.storeId, stores.id)).where(inArray(storeOrders.status, ["preparing", "shipped", "delivered"])).orderBy(desc(storeOrders.createdAt)).limit(80),
  ]);
  const config = Object.fromEntries(settings.map((s) => [s.key, s.value]));
  return <div className="stack"><div className="panel-grid"><div className="surface surface-pad"><h2 className="surface-title">EFT hesap bilgileri</h2><p className="muted small-text">Gerçek hesap bilgileri girilmeden EFT checkout açılmaz.</p><form action={saveBankDetailsAction}><label className="form-field"><span>Banka adı *</span><input name="bankName" defaultValue={config.bank_name || ""} required /></label><label className="form-field"><span>Hesap sahibi *</span><input name="accountHolder" defaultValue={config.bank_holder || ""} required /></label><label className="form-field"><span>TR IBAN *</span><input name="iban" defaultValue={config.bank_iban || ""} required placeholder="TR..." /></label><button className="btn btn-dark btn-small" type="submit">Banka Bilgilerini Kaydet</button></form></div><div className="surface surface-pad"><h2 className="surface-title">Hakediş ve komisyon ayarları</h2><form action={savePayoutPeriodAction}><label className="form-field"><span>Ödeme periyodu (gün)</span><input name="days" type="number" min="1" max="365" defaultValue={config.payout_interval_days || "30"} required /></label><button className="btn btn-outline btn-small" type="submit">Periyodu Kaydet</button></form><div className="divider" /><form action={updateCommissionAction}><label className="form-field"><span>Mağaza *</span><select name="storeId" required defaultValue=""><option value="" disabled>Mağaza seçin</option>{storesList.map((s) => <option key={s.id} value={s.id}>{s.name} · mevcut %{s.rate}</option>)}</select></label><label className="form-field"><span>Komisyon oranı %</span><input type="number" name="rate" min="0" max="100" step="0.01" required /></label><button className="btn btn-outline btn-small" type="submit">Mağaza Oranını Güncelle</button></form></div></div>
    <div className="surface surface-pad"><h2 className="surface-title">Mağaza bakiyeleri</h2>{balances.length ? <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Mağaza</th><th>Bekleyen</th><th>Kullanılabilir</th><th>Ödenen</th><th>Komisyon</th><th>İade kesintisi</th><th>Payout oluştur</th></tr></thead><tbody>{balances.map(({ balance, storeName }) => <tr key={balance.storeId}><td><strong>{storeName}</strong></td><td>{formatPrice(balance.pendingAmount)}</td><td>{formatPrice(balance.availableAmount)}</td><td>{formatPrice(balance.paidTotal)}</td><td>{formatPrice(balance.commissionTotal)}</td><td>{formatPrice(balance.refundTotal)}</td><td><form action={createPayoutAction} className="inline-form"><input type="hidden" name="storeId" value={balance.storeId} /><input className="mini-input" name="amount" type="number" step="0.01" min="0.01" max={balance.availableAmount} placeholder="Tutar" required /><button className="btn btn-dark btn-small" type="submit">Ayır</button></form></td></tr>)}</tbody></table></div> : <p className="muted small-text">Henüz mağaza bakiyesi bulunmuyor.</p>}</div>
    <div className="panel-grid"><div className="surface surface-pad"><h2 className="surface-title">Payout işlemleri</h2>{payoutRows.length ? payoutRows.map(({ payout, storeName }) => <div className="list-card" key={payout.id}><div><h3>{storeName} · {formatPrice(payout.amount)}</h3><p>{formatDate(payout.createdAt)} · {payout.status}</p></div>{payout.status === "pending" ? <form action={markPayoutPaidAction} className="inline-form"><input type="hidden" name="id" value={payout.id} /><input name="bankReference" className="mini-input" placeholder="Dekont ref." required /><button className="btn btn-accent btn-small" type="submit">Ödendi</button></form> : <span className="status-badge status-paid">Ödendi</span>}</div>) : <p className="muted small-text">Henüz payout bulunmuyor.</p>}</div>
      <div className="surface surface-pad"><h2 className="surface-title">Komisyon faturaları</h2>{invoiceRows.length ? invoiceRows.map(({ invoice, storeName }) => <div className="list-card" key={invoice.id}><div><h3>{storeName} · {formatPrice(invoice.amount)}</h3><p>{invoice.invoiceNumber || "Taslak"} · {invoice.status}</p></div>{invoice.status === "draft" ? <form action={issueCommissionInvoiceAction} className="stack" style={{ gap: 5 }}><input type="hidden" name="id" value={invoice.id} /><input name="invoiceNumber" className="mini-input" placeholder="Fatura no" required /><input name="pdfUrl" className="mini-input" style={{ width: 160 }} type="url" placeholder="HTTPS PDF URL" required /><button className="btn btn-dark btn-small" type="submit">Gerçek Faturayı Kaydet</button></form> : <span className="status-badge status-paid">Düzenlendi</span>}</div>) : <p className="muted small-text">Teslimat sonrası komisyon fatura taslakları burada görünür.</p>}</div></div>
    <div className="surface surface-pad"><h2 className="surface-title">Banka iadesi / ters finans hareketi</h2><p className="muted small-text">Yalnızca gerçek banka iadesi yapılıp dekont doğrulandıktan sonra kaydedin. Kart iadeleri iyzico üzerinden ayrıca yapılmalıdır.</p><form action={recordRefundAction} className="form-actions"><select name="storeOrderId" className="form-input" required style={{ maxWidth: 400 }} defaultValue=""><option value="" disabled>Mağaza alt siparişini seçin</option>{refundRows.filter((r) => r.method === "bank_transfer").map((r) => <option key={r.part.id} value={r.part.id}>#{r.orderNumber} · {r.storeName} · {formatPrice(r.part.subtotal)} · {r.part.status}</option>)}</select><input name="reference" className="form-input" style={{ maxWidth: 250 }} placeholder="Doğrulanmış iade dekontu" required /><button className="btn btn-danger" type="submit">İade Hareketini Kaydet</button></form></div>
  </div>;
}

async function QuotesTab() {
  const [requests, offers] = await Promise.all([db.select({ request: quoteRequests, customer: users.email }).from(quoteRequests).innerJoin(users, eq(quoteRequests.customerId, users.id)).orderBy(desc(quoteRequests.createdAt)).limit(60), db.select({ offer: quoteOffers, storeName: stores.name }).from(quoteOffers).innerJoin(stores, eq(quoteOffers.storeId, stores.id)).orderBy(desc(quoteOffers.createdAt)).limit(100)]);
  return <div className="panel-grid"><div className="surface surface-pad"><h2 className="surface-title">Müşteri talepleri</h2>{requests.length ? requests.map(({ request, customer }) => <div className="list-card" key={request.id}><div><h3>{request.description.slice(0, 75)}</h3><p>{customer} · {request.city} · {formatDate(request.createdAt)}</p></div><span className="status-badge">{request.status}</span></div>) : <p className="muted small-text">Talep yok.</p>}</div><div className="surface surface-pad"><h2 className="surface-title">Mağaza teklifleri (yalnızca admin)</h2>{offers.length ? offers.map(({ offer, storeName }) => <div className="list-card" key={offer.id}><div><h3>{storeName} · {offer.brand}</h3><p>{formatPrice(offer.price)} · {productTypeLabels[offer.productType]} · {formatDate(offer.createdAt)}</p></div><span className="status-badge">{offer.status}</span></div>) : <p className="muted small-text">Teklif yok.</p>}</div></div>;
}

async function LiveTab() {
  const calls = await db.select({ id: callRequests.id, status: callRequests.status, store: stores.name, customer: users.name, createdAt: callRequests.createdAt }).from(callRequests).innerJoin(stores, eq(callRequests.storeId, stores.id)).innerJoin(users, eq(callRequests.customerId, users.id)).orderBy(desc(callRequests.createdAt));
  return <div className="surface surface-pad"><h2 className="surface-title">Live görüşme talepleri</h2>{calls.length ? calls.map((c) => <Link href={`/canli/${c.id}`} className="list-card" key={c.id}><div><h3>{c.customer} ↔ {c.store}</h3><p>{formatDate(c.createdAt)} · {c.status}</p></div><ArrowRight size={16} /></Link>) : <EmptyState title="Henüz Live talebi yok" description="Görüşme talepleri burada listelenecek." />}</div>;
}

async function AuditTab() {
  const logs = await db.select({ log: auditLogs, actorEmail: users.email }).from(auditLogs).leftJoin(users, eq(auditLogs.actorId, users.id)).orderBy(desc(auditLogs.createdAt)).limit(200);
  return <div className="surface surface-pad"><h2 className="surface-title">Değiştirilemez işlem geçmişi</h2>{logs.length ? <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Tarih</th><th>İşlem</th><th>Aktör</th><th>Kayıt</th></tr></thead><tbody>{logs.map(({ log, actorEmail }) => <tr key={log.id}><td>{formatDate(log.createdAt)}</td><td><strong>{log.action}</strong></td><td>{actorEmail || "Sistem / sağlayıcı"}</td><td>{log.entityType}<div className="muted">{log.entityId.slice(0, 16)}</div></td></tr>)}</tbody></table></div> : <EmptyState title="Henüz işlem kaydı yok" description="Ürün, sipariş, finans ve yönetim değişiklikleri burada izlenecek." />}</div>;
}
