import Link from "next/link";
import { and, count, desc, eq, inArray } from "drizzle-orm";
import { ArrowRight, BadgeCheck, Boxes, ClipboardList, FileSpreadsheet, Headphones, Landmark, Package, Plus, Store, Truck, Wallet } from "lucide-react";
import { db } from "@/db";
import { callRequests, commissionInvoices, csvImports, oemProductRequests, orderItems, orders, payments, products, quoteOffers, quoteRequests, shipments, storeBalances, storeLedger, storeOrders, storePayouts, storeProducts, storeSalesInvoices, users } from "@/db/schema";
import { createShipmentAction, createStoreOfferAction, requestOemAction, submitQuoteOfferAction, updateStoreOfferAction, updateStoreProfileAction, uploadSalesInvoiceAction } from "@/app/actions/store";
import { CsvUploader } from "@/components/csv-uploader";
import { EmptyState, TypeBadge } from "@/components/catalog-ui";
import { requireStore } from "@/lib/auth";
import { formatDate, formatPrice, productTypeLabels } from "@/lib/core";

export const dynamic = "force-dynamic";
const tabs = [ ["genel", "Genel Bakış"], ["urunler", "Ürünler"], ["yukle", "CSV Yükleme"], ["siparisler", "Siparişler & Kargo"], ["teklifler", "Teklif Talepleri"], ["canli", "Live Talepleri"], ["finans", "Bakiye & Faturalar"], ["ayarlar", "Ayarlar"] ] as const;
const statusLabels: Record<string, string> = { pending: "Onay bekliyor", approved: "Onaylı", suspended: "Askıda", awaiting_payment: "Ödeme bekleniyor", preparing: "Hazırlanıyor", shipped: "Kargoda", delivered: "Teslim edildi", refunded: "İade edildi", active: "Aktif", closed: "Bitti", requested: "Bekliyor" };
export default async function StorePanelPage({ searchParams }: { searchParams: Promise<{ tab?: string; error?: string; success?: string }> }) {
  const { user, store } = await requireStore(), query = await searchParams;
  const tab = tabs.some(([key]) => key === query.tab) ? query.tab || "genel" : "genel";
  const [[balance], [productCount], [orderCount]] = await Promise.all([
    db.select().from(storeBalances).where(eq(storeBalances.storeId, store.id)),
    db.select({ total: count() }).from(storeProducts).where(eq(storeProducts.storeId, store.id)),
    db.select({ total: count() }).from(storeOrders).where(eq(storeOrders.storeId, store.id)),
  ]);
  return <main className="shell page-main"><div className="breadcrumb"><Link href="/">Ana sayfa</Link> / Mağaza paneli</div><div className="page-heading page-heading-row"><div><span className="eyebrow"><Store size={14} /> MAĞAZA PANELİ</span><h1>{store.name}</h1><p>Ürünlerini, siparişlerini, tekliflerini ve teslimat sonrası hakedişlerini yönet.</p></div><span className={`status-badge status-${store.status}`}>{statusLabels[store.status]}</span></div>
    {store.status !== "approved" && <div className="notice notice-info">Mağaza başvurunuz {statusLabels[store.status]?.toLowerCase()}. Ürün satışı ve teklif verme için yönetici onayı gereklidir.</div>}
    {query.error && <div className="notice notice-error">{query.error}</div>}{query.success && <div className="notice notice-success"><BadgeCheck size={16} /> {query.success}</div>}
    <nav className="panel-nav">{tabs.map(([key, label]) => <Link key={key} href={`/magaza-paneli?tab=${key}`} className={tab === key ? "active" : ""}>{label}</Link>)}</nav>
    {tab === "genel" && <div className="stack"><div className="metric-grid"><div className="metric-card"><span><Boxes size={15} /> Teklifler</span><strong>{productCount.total}</strong><small>Merkezi kataloğa bağlı</small></div><div className="metric-card"><span><Package size={15} /> Mağaza siparişleri</span><strong>{orderCount.total}</strong><small>Yalnızca size ait siparişler</small></div><div className="metric-card"><span><Wallet size={15} /> Kullanılabilir bakiye</span><strong>{formatPrice(balance?.availableAmount || "0")}</strong><small>Teslimat sonrası hakediş</small></div><div className="metric-card"><span><Landmark size={15} /> Bekleyen hakediş</span><strong>{formatPrice(balance?.pendingAmount || "0")}</strong><small>Teslimat bekleyen satışlar</small></div></div><div className="panel-grid"><Link href="/magaza-paneli?tab=urunler" className="surface surface-pad"><Boxes size={25} color="#708e62" /><h3 className="surface-title" style={{ marginTop: 15 }}>Ürünlerini yönet</h3><p className="muted small-text">OEM'e bağlı marka ve ürün tipi tekliflerini oluştur.</p><span className="section-link">Ürünlere git <ArrowRight size={15} /></span></Link><Link href="/magaza-paneli?tab=yukle" className="surface surface-pad"><FileSpreadsheet size={25} color="#708e62" /><h3 className="surface-title" style={{ marginTop: 15 }}>CSV ile hızlı yükle</h3><p className="muted small-text">Standart şablonu indir, önizle ve onayla.</p><span className="section-link">CSV yükleme <ArrowRight size={15} /></span></Link></div></div>}
    {tab === "urunler" && <StoreProductsTab storeId={store.id} approved={store.status === "approved"} />}
    {tab === "yukle" && <ImportsTab storeId={store.id} approved={store.status === "approved"} />}
    {tab === "siparisler" && <StoreOrdersTab storeId={store.id} />}
    {tab === "teklifler" && <QuoteRequestsTab storeId={store.id} approved={store.status === "approved"} />}
    {tab === "canli" && <CallsTab storeId={store.id} />}
    {tab === "finans" && <FinanceTab storeId={store.id} rate={store.commissionRate} balance={balance} />}
    {tab === "ayarlar" && <div className="surface surface-pad" style={{ maxWidth: 590 }}><h2 className="surface-title">Mağaza ayarları</h2><form action={updateStoreProfileAction}><label className="form-field"><span>Mağaza adı</span><input value={store.name} readOnly /></label><label className="form-field"><span>Şehir</span><input value={store.city || ""} readOnly /></label><label className="form-field"><span>Mağaza açıklaması</span><textarea name="description" defaultValue={store.description || ""} /></label><label className="form-field"><span>Hakediş IBAN'ı</span><input name="iban" defaultValue={store.iban || ""} placeholder="TR..." /></label><button className="btn btn-dark" type="submit">Bilgileri Kaydet</button></form></div>}
  </main>;
}

async function StoreProductsTab({ storeId, approved }: { storeId: string; approved: boolean }) {
  const offers = await db.select({ offer: storeProducts, productName: products.productName, oemNo: products.oemNo }).from(storeProducts).innerJoin(products, eq(storeProducts.catalogProductId, products.id)).where(eq(storeProducts.storeId, storeId)).orderBy(desc(storeProducts.createdAt));
  return <div className="stack"><div className="surface surface-pad"><h2 className="surface-title"><Plus size={17} style={{ display: "inline" }} /> Kataloğa bağlı teklif ekle</h2><p className="muted small-text">Ürün adı merkezi katalogdan gelir. Aynı OEM için farklı markalara ayrı SKU ile teklif açabilirsin.</p><form action={createStoreOfferAction}><div className="field-grid three"><label className="form-field"><span>OEM / Parça No *</span><input name="oemNo" required placeholder="Katalogdaki OEM" /></label><label className="form-field"><span>Marka *</span><input name="brand" required placeholder="Üretici markası" /></label><label className="form-field"><span>Ürün Tipi *</span><select name="productType" required defaultValue=""><option value="" disabled>Seçiniz</option>{Object.entries(productTypeLabels).map(([key, value]) => <option key={key} value={key}>{value}</option>)}</select></label><label className="form-field"><span>Mağaza SKU *</span><input name="sku" required placeholder="Benzersiz SKU" /></label><label className="form-field"><span>Fiyat (₺) *</span><input name="price" required type="number" min="0.01" step="0.01" /></label><label className="form-field"><span>Stok *</span><input name="stock" required type="number" min="0" step="1" /></label><label className="form-field"><span>Barkod</span><input name="barcode" /></label><label className="form-field"><span>Görsel URL (HTTPS)</span><input name="imageUrl" type="url" placeholder="https://..." /></label></div><button className="btn btn-accent" type="submit" disabled={!approved}>Teklifi Kaydet <ArrowRight size={15} /></button></form></div>
    <div className="surface surface-pad"><h2 className="surface-title">Ürün tekliflerim ({offers.length})</h2>{offers.length ? <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Merkezi ürün</th><th>Marka / Tip</th><th>SKU</th><th>Fiyat</th><th>Stok</th><th>Durum / Düzenle</th></tr></thead><tbody>{offers.map(({ offer, productName, oemNo }) => <tr key={offer.id}><td><Link href={`/parca/${offer.catalogProductId}`}><strong>{productName}</strong></Link><div className="muted">OEM: {oemNo}</div></td><td><strong>{offer.brand}</strong><div style={{ marginTop: 5 }}><TypeBadge type={offer.productType} compact /></div></td><td>{offer.storeSku}</td><td><strong>{formatPrice(offer.price)}</strong></td><td>{offer.stock}</td><td><span className={`status-badge status-${offer.active ? "active" : "suspended"}`}>{offer.active ? "Aktif" : "Pasif"}</span><details style={{ marginTop: 8 }}><summary className="small-text" style={{ cursor: "pointer", fontWeight: 800 }}>Düzenle</summary><form action={updateStoreOfferAction} style={{ minWidth: 165, paddingTop: 9 }}><input type="hidden" name="id" value={offer.id} /><label className="form-field"><span>Fiyat (₺)</span><input name="price" type="number" step="0.01" min="0.01" defaultValue={offer.price} required /></label><label className="form-field"><span>Stok</span><input name="stock" type="number" min="0" defaultValue={offer.stock} required /></label><label className="form-field"><span>Ürün Tipi</span><select name="productType" defaultValue={offer.productType}>{Object.entries(productTypeLabels).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label><label className="checkbox-row"><input type="checkbox" name="active" defaultChecked={offer.active} /> Aktif</label><button className="btn btn-dark btn-small" style={{ marginTop: 10 }} type="submit">Kaydet</button></form></details></td></tr>)}</tbody></table></div> : <EmptyState title="Henüz teklif yok" description="Merkezi katalogdaki bir OEM numarasıyla ilk mağaza teklifini ekle veya CSV şablonunu kullan." />}</div>
  </div>;
}

async function ImportsTab({ storeId, approved }: { storeId: string; approved: boolean }) {
  const [imports, requests] = await Promise.all([db.select().from(csvImports).where(eq(csvImports.storeId, storeId)).orderBy(desc(csvImports.createdAt)).limit(20), db.select().from(oemProductRequests).where(eq(oemProductRequests.storeId, storeId)).orderBy(desc(oemProductRequests.createdAt)).limit(20)]);
  return <div className="stack">{approved ? <CsvUploader /> : <div className="notice notice-info">CSV yükleme mağaza onaylandıktan sonra açılır.</div>}
    <div className="surface surface-pad"><h2 className="surface-title">Katalogda olmayan OEM için talep</h2><form action={requestOemAction} className="field-grid"><label className="form-field"><span>OEM No *</span><input name="oemNo" required placeholder="Bilinmeyen OEM numarası" /></label><label className="form-field"><span>Önerilen ürün adı (yalnızca admin incelemesi için)</span><input name="suggestedName" placeholder="Ürün adı otomatik oluşturulmaz" /></label><button className="btn btn-outline" type="submit">OEM Talebi Oluştur <ArrowRight size={15} /></button></form></div>
    <div className="panel-grid"><div className="surface surface-pad"><h2 className="surface-title">İçe aktarma geçmişi</h2>{imports.length ? imports.map((i) => <div className="list-card" key={i.id}><div><h3>{i.fileName}</h3><p>{formatDate(i.createdAt)} · {i.totalRows} satır</p></div><span className="status-badge status-approved">{i.importedRows} yüklendi · {i.failedRows} hata</span></div>) : <p className="muted small-text">Henüz CSV yükleme yapılmadı.</p>}</div><div className="surface surface-pad"><h2 className="surface-title">OEM ürün taleplerim</h2>{requests.length ? requests.map((r) => <div className="list-card" key={r.id}><div><h3>{r.oemNo}</h3><p>{r.suggestedName || "Ürün adı bekleniyor"}</p></div><span className={`status-badge status-${r.status}`}>{statusLabels[r.status] || r.status}</span></div>) : <p className="muted small-text">Henüz OEM talebiniz yok.</p>}</div></div>
  </div>;
}

async function StoreOrdersTab({ storeId }: { storeId: string }) {
  const parts = await db.select({ part: storeOrders, orderNumber: orders.orderNumber, customerName: orders.shippingName, customerPhone: orders.shippingPhone, city: orders.shippingCity, address: orders.shippingAddress, paymentMethod: orders.paymentMethod }).from(storeOrders).innerJoin(orders, eq(storeOrders.orderId, orders.id)).where(eq(storeOrders.storeId, storeId)).orderBy(desc(storeOrders.createdAt)).limit(100);
  const ids = parts.map((p) => p.part.id);
  const [items, tracking, invoices] = await Promise.all([ids.length ? db.select().from(orderItems).where(inArray(orderItems.storeOrderId, ids)) : [], ids.length ? db.select().from(shipments).where(inArray(shipments.storeOrderId, ids)) : [], ids.length ? db.select().from(storeSalesInvoices).where(inArray(storeSalesInvoices.storeOrderId, ids)) : []]);
  return <div className="stack">{parts.length ? parts.map(({ part, orderNumber, customerName, customerPhone, city, address }) => <div className="surface surface-pad" key={part.id}><div className="page-heading-row"><div><span className="eyebrow"><Package size={14} /> SİPARİŞ #{orderNumber}</span><h2 style={{ fontSize: 17, fontWeight: 800, marginTop: 6 }}>{customerName} · {formatPrice(part.subtotal)}</h2><p className="muted small-text">{city} · {address} · {customerPhone}</p></div><span className={`status-badge status-${part.status}`}>{statusLabels[part.status] || part.status}</span></div><div className="divider" />
      {items.filter((i) => i.storeOrderId === part.id).map((item) => <div className="order-line" key={item.id}><span>{item.productName} · {item.brand} · <TypeBadge type={item.productType} compact /> · {item.quantity} adet</span><strong>{formatPrice(item.lineTotal)}</strong></div>)}
      <div className="order-line"><span>Komisyon (sipariş anı)</span><strong>{formatPrice(part.commissionTotal)}</strong></div><div className="order-line"><span>Teslimat sonrası hakediş</span><strong>{formatPrice(part.payoutAmount)}</strong></div>
      {tracking.filter((t) => t.storeOrderId === part.id).map((t) => <div className="notice notice-info" key={t.id}><Truck size={16} /> {t.carrier} · {t.trackingNumber} · {t.status}</div>)}
      {invoices.filter((i) => i.storeOrderId === part.id).map((i) => <div className="notice notice-success" key={i.id}><BadgeCheck size={16} /> Satış faturan: {i.invoiceNumber}</div>)}
      <div className="panel-grid" style={{ marginTop: 18 }}><div><h3 style={{ fontSize: 12, fontWeight: 800, marginBottom: 9 }}>Kargo bilgisi ekle</h3><form action={createShipmentAction}><input type="hidden" name="storeOrderId" value={part.id} /><div className="field-grid"><label className="form-field"><span>Kargo firması</span><input name="carrier" placeholder="Firma adı" required /></label><label className="form-field"><span>Takip numarası</span><input name="trackingNumber" placeholder="Takip no" required /></label></div><button type="submit" className="btn btn-outline btn-small" disabled={!(["preparing", "shipped"].includes(part.status))}>Kargoyu Kaydet</button></form></div><div><h3 style={{ fontSize: 12, fontWeight: 800, marginBottom: 9 }}>Müşteriye satış faturası</h3><form action={uploadSalesInvoiceAction}><input type="hidden" name="storeOrderId" value={part.id} /><div className="field-grid"><label className="form-field"><span>Fatura numarası</span><input name="invoiceNumber" defaultValue={invoices.find((i) => i.storeOrderId === part.id)?.invoiceNumber || ""} required /></label><label className="form-field"><span>PDF bağlantısı (HTTPS)</span><input name="pdfUrl" type="url" defaultValue={invoices.find((i) => i.storeOrderId === part.id)?.pdfUrl || ""} placeholder="https://..." /></label></div><button type="submit" className="btn btn-outline btn-small" disabled={part.status === "awaiting_payment"}>Faturayı Kaydet</button></form></div></div>
    </div>) : <EmptyState title="Henüz sipariş yok" description="Müşteriler mağazanızdan ürün satın aldığında alt siparişler burada görünür." />}</div>;
}

async function QuoteRequestsTab({ storeId, approved }: { storeId: string; approved: boolean }) {
  const [requests, ownOffers] = await Promise.all([approved ? db.select().from(quoteRequests).where(eq(quoteRequests.status, "open")).orderBy(desc(quoteRequests.createdAt)).limit(60) : Promise.resolve([]), db.select().from(quoteOffers).where(eq(quoteOffers.storeId, storeId))]);
  return <div className="stack"><div className="notice notice-info">Talep bilgileri mağazalara açıktır; rakip mağazaların fiyatları, stokları ve teklifleri bu panelde gösterilmez.</div>{requests.length ? requests.map((r) => { const mine = ownOffers.find((o) => o.quoteRequestId === r.id); return <div className="surface surface-pad" key={r.id}><div className="page-heading-row"><div><span className="eyebrow"><ClipboardList size={13} /> {r.city} · {formatDate(r.createdAt)}</span><h3 style={{ fontWeight: 800, fontSize: 16, margin: "8px 0" }}>{r.description}</h3><p className="muted small-text">{[r.vehicleBrand, r.vehicleModel, r.vehicleYear].filter(Boolean).join(" ") || "Araç belirtilmedi"} · OEM: {r.oemNo || "-"} · {r.quantity} adet</p></div>{r.photoUrl && <img src={r.photoUrl} alt="Parça fotoğrafı" style={{ width: 95, height: 75, objectFit: "cover", borderRadius: 8 }} />}</div>
      {mine ? <div className="notice notice-success">Bu talebe kendi teklifinizi verdiniz: {formatPrice(mine.price)} · <TypeBadge type={mine.productType} compact /></div> : approved ? <details style={{ marginTop: 13 }}><summary className="btn btn-dark btn-small" style={{ display: "inline-flex", cursor: "pointer" }}>Bu Talebe Teklif Ver <ArrowRight size={14} /></summary><form action={submitQuoteOfferAction} style={{ paddingTop: 18 }}><input type="hidden" name="requestId" value={r.id} /><div className="field-grid three"><label className="form-field"><span>Marka *</span><input name="brand" required /></label><label className="form-field"><span>Ürün Tipi *</span><select name="productType" required defaultValue=""><option value="" disabled>Seçiniz</option>{Object.entries(productTypeLabels).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label><label className="form-field"><span>Birim fiyat (₺) *</span><input type="number" min="0.01" step="0.01" name="price" required /></label><label className="form-field"><span>Stok *</span><input name="stock" type="number" min="1" required /></label><label className="form-field"><span>Hazırlık (gün) *</span><input name="preparationDays" type="number" min="0" max="90" defaultValue="1" required /></label><label className="form-field"><span>Geçerlilik (gün) *</span><input name="validDays" type="number" min="1" max="90" defaultValue="7" required /></label><label className="form-field"><span>Merkezi OEM (varsa)</span><input name="catalogOem" placeholder="İsteğe bağlı" /></label><label className="form-field"><span>Kargo bilgisi</span><input name="shippingInfo" /></label></div><label className="form-field"><span>Not</span><textarea name="notes" /></label><button type="submit" className="btn btn-accent">Teklifi Gönder</button></form></details> : <p className="muted small-text">Teklif verebilmek için mağaza onayı bekleyin.</p>}
    </div>; }) : <EmptyState title="Açık teklif talebi yok" description="Müşteriler bulunamayan parçalar için talep oluşturduğunda burada görünecek." />}</div>;
}

async function CallsTab({ storeId }: { storeId: string }) {
  const calls = await db.select({ call: callRequests, customer: users.name, productName: products.productName }).from(callRequests).innerJoin(users, eq(callRequests.customerId, users.id)).leftJoin(storeProducts, eq(callRequests.storeProductId, storeProducts.id)).leftJoin(products, eq(storeProducts.catalogProductId, products.id)).where(eq(callRequests.storeId, storeId)).orderBy(desc(callRequests.createdAt));
  return <div className="surface surface-pad"><h2 className="surface-title">Live satış temsilcisi talepleri</h2>{calls.length ? calls.map(({ call, customer, productName }) => <Link href={`/canli/${call.id}`} key={call.id} className="list-card"><div><h3>{customer} · {productName || "Ürün danışmanlığı"}</h3><p>{formatDate(call.createdAt)} · Mağazanızla birebir görüşme</p></div><span className={`status-badge status-${call.status}`}>{statusLabels[call.status] || call.status}</span></Link>) : <EmptyState icon={<Headphones size={27} />} title="Henüz görüşme talebi yok" description="Müşteriler mağaza teklifinden görüşme istediğinde burada görünecek." />}</div>;
}

async function FinanceTab({ storeId, rate, balance }: { storeId: string; rate: string; balance: typeof storeBalances.$inferSelect | undefined }) {
  const [ledger, payouts, invoices] = await Promise.all([db.select().from(storeLedger).where(eq(storeLedger.storeId, storeId)).orderBy(desc(storeLedger.createdAt)).limit(70), db.select().from(storePayouts).where(eq(storePayouts.storeId, storeId)).orderBy(desc(storePayouts.createdAt)), db.select().from(commissionInvoices).where(eq(commissionInvoices.storeId, storeId)).orderBy(desc(commissionInvoices.createdAt))]);
  return <div className="stack"><div className="metric-grid"><div className="metric-card"><span>Bekleyen hakediş</span><strong>{formatPrice(balance?.pendingAmount || 0)}</strong></div><div className="metric-card"><span>Kullanılabilir bakiye</span><strong>{formatPrice(balance?.availableAmount || 0)}</strong></div><div className="metric-card"><span>Ödenen toplam</span><strong>{formatPrice(balance?.paidTotal || 0)}</strong></div><div className="metric-card"><span>Toplam komisyon</span><strong>{formatPrice(balance?.commissionTotal || 0)}</strong></div></div><div className="notice notice-info">Varsayılan komisyon oranınız %{rate}. Her siparişin oranı sipariş anında sabitlenir. Hakediş yalnızca ilgili mağaza alt siparişi teslim edildiğinde oluşur.</div>
    <div className="panel-grid"><div className="surface surface-pad"><h2 className="surface-title">Bakiye hareketleri</h2>{ledger.length ? <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Tarih</th><th>İşlem</th><th>Tutar</th></tr></thead><tbody>{ledger.map((l) => <tr key={l.id}><td>{formatDate(l.createdAt)}</td><td><strong>{l.type.replace(/_/g, " ")}</strong><div className="muted">{l.description}</div></td><td><strong>{formatPrice(l.amount)}</strong></td></tr>)}</tbody></table></div> : <p className="muted small-text">Henüz finans hareketi yok.</p>}</div><div className="stack"><div className="surface surface-pad"><h2 className="surface-title">Payout geçmişi</h2>{payouts.length ? payouts.map((p) => <div className="list-card" key={p.id}><div><h3>{formatPrice(p.amount)}</h3><p>{formatDate(p.createdAt)} {p.bankReference && `· ${p.bankReference}`}</p></div><span className={`status-badge status-${p.status}`}>{p.status === "paid" ? "Ödendi" : "Bekliyor"}</span></div>) : <p className="muted small-text">Henüz payout kaydı yok.</p>}</div><div className="surface surface-pad"><h2 className="surface-title">DampingVar komisyon faturaları</h2>{invoices.length ? invoices.map((i) => <div className="list-card" key={i.id}><div><h3>{formatPrice(i.amount)}</h3><p>{i.invoiceNumber || "Fatura taslağı"} · {formatDate(i.createdAt)}</p></div>{i.pdfUrl ? <a href={i.pdfUrl} target="_blank" rel="noopener noreferrer" className="section-link">PDF ↗</a> : <span className="status-badge">Taslak</span>}</div>) : <p className="muted small-text">Henüz komisyon faturası yok.</p>}</div></div></div>
  </div>;
}
